spring:
  datasource:
      url: jdbc:postgresql://192.168.15.3:5432/postgres
      username: postgres
      password: postgres
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: create-drop